import axios from 'axios'
import Head from 'next/head'
import Login from '../components/layouts/Login/Login'

export default function Connection () {
    
    return (
        <div>
          <Head>
            <title>Dunes - Connexion</title>
            <meta name="description" content="Generated by create next app" />
          {/* Global Site Tag (gtag.js) - Google Analytics */}
          <script
            async
            src={`https://www.googletagmanager.com/gtag/js?id=${process.env.NEXT_PUBLIC_ANALI}`}
          />
          <script
            dangerouslySetInnerHTML={{
              __html: `
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', '${process.env.NEXT_PUBLIC_ANALI}', {
              page_path: window.location.pathname,
            });
          `,
            }}
          />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main id="scroll">
              <Login/>
          </main>
        </div>
    )
}