import Head from 'next/head'
import Form from '../components/layouts/contact/Form/Form'

export default function Contact () {
    
    return (
        <div>
          <Head>
            <title>Dunes</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main style={{position: "relative", height: "100vh", width: "100%"}} id="scroll">
              <Form/>
              <img src="/assets/img/complexe.webp" style={{position: "absolute", left: "0", top:"0", height: "100%", width:"50%", objectFit:"cover"}}/>
          </main>
        </div>
    )
}