import Head from 'next/head'

export default function Contact () {
    
    return (
        <div>
          <Head>
            <title>Dunes</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main id="scroll">

          </main>
        </div>
    )
}