import Head from "next/head";
import Banner from "../components/global/Banner/Banner";
import LeftLayout from "../components/layouts/Home/leftLayoiut/LeftLayout";
import RightLayout from "../components/layouts/Home/rightLayout/rightLayout";

export default function Home() {
  const layouts = [
    {
      title: "haute <span>intensité</span>",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis lorem quam. Nullam velit ante, scelerisque nec velit a, imperdiet pretium ipsum. Sed aliquam dui velit, ac finibus tellus vehicula quis. Quisque lacinia sem nec turpis fermentum gravida. Integer faucibus iaculis suscipit. In aliquet eleifend lacus sed laoreet. Aliquam consectetur, ipsum sodales pellentesque auctor, libero ligula suscipit ipsum, eu vehicula ex ipsum sit amet ipsum. Donec volutpat risus placerat lorem faucibus malesuada",
      img: "/assets/img/intensity.jpeg",
      button: {
        link: "",
        label: "Decouvrir nos programme",
      },
      left: false,
    },
    {
      title: "staff de <span>qualité</span>",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis lorem quam. Nullam velit ante, scelerisque nec velit a, imperdiet pretium ipsum. Sed aliquam dui velit, ac finibus tellus vehicula quis. Quisque lacinia sem nec turpis fermentum gravida. Integer faucibus iaculis suscipit. In aliquet eleifend lacus sed laoreet. Aliquam consectetur, ipsum sodales pellentesque auctor, libero ligula suscipit ipsum, eu vehicula ex ipsum sit amet ipsum. Donec volutpat risus placerat lorem faucibus malesuada",
      img: "/assets/img/coach.jpeg",
      button: {
        link: "",
        label: "Voir le staff",
      },
      left: true,
    },

    {
      title: "Notre <span>complexe</span>",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis lorem quam. Nullam velit ante, scelerisque nec velit a, imperdiet pretium ipsum. Sed aliquam dui velit, ac finibus tellus vehicula quis. Quisque lacinia sem nec turpis fermentum gravida. Integer faucibus iaculis suscipit. In aliquet eleifend lacus sed laoreet. Aliquam consectetur, ipsum sodales pellentesque auctor, libero ligula suscipit ipsum, eu vehicula ex ipsum sit amet ipsum. Donec volutpat risus placerat lorem faucibus malesuada",
      img: "/assets/img/dunes.jpeg",
      button: {
        link: "",
        label: "Le complexe",
      },
      left: false,
    },
    {
      title: "prix <br/><span>adapté</span>",
      desc: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis lorem quam. Nullam velit ante, scelerisque nec velit a, imperdiet pretium ipsum. Sed aliquam dui velit, ac finibus tellus vehicula quis. Quisque lacinia sem nec turpis fermentum gravida. Integer faucibus iaculis suscipit. In aliquet eleifend lacus sed laoreet. Aliquam consectetur, ipsum sodales pellentesque auctor, libero ligula suscipit ipsum, eu vehicula ex ipsum sit amet ipsum. Donec volutpat risus placerat lorem faucibus malesuada",
      img: "/assets/img/tarifsgirl.jpg",
      button: {
        link: "",
        label: "Decouvrir nos programme",
      },
      left: true,
    },
  ];

  return (
    <div>
      <Head>
        <title>Dunes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="scroll">
        <Banner videoSrc="/assets/video/banner.mp4"/>
        {layouts.map((el, i) => {
          return el.left ? (
            <LeftLayout
              i={i}
              img={el.img}
              title={el.title}
              desc={el.desc}
              buttonString={el.button.label}
            />
          ) : (
            <RightLayout
              i={i}
              img={el.img}
              title={el.title}
              desc={el.desc}
              buttonString={el.button.label}
            />
          );
        })}
      </main>
    </div>
  );
}
