import Head from "next/head";
import Banner from "../components/global/Banner/Banner";
import LeftLayout from "../components/layouts/Home/leftLayoiut/LeftLayout";
import RightLayout from "../components/layouts/Home/rightLayout/rightLayout";

export default function Home() {
  const layouts = [
    {
      title: "Accompagnement vers <span>vos objectifs</span>",
      desc: "Tu veux perdre du poids? Tu veux prendre de la masse musculaire? Tu veux passer un cap dans ta pratique sportive ? Tu désires découvrir les entraînements fonctionnels ?",
      img: "/assets/img/intensity.webp",
      button: {
        link: "/programmes",
        label: "Nos programmes",
      },
      left: false,
    },
    {
      title: "staff de <span>qualité</span>",
      desc: "Nos coachs vous accompagnent lors des classes afin de vous aider à atteindre vos objectifs grâce à leur méthode unique sur la ville de Saint-Quentin.",
      img: "/assets/img/staff.webp",
      button: {
        link: "/staff",
        label: "Voir le staff",
      },
      left: true,
    },

    {
      title: "Notre <span>complexe</span>",
      desc: "Dunes vous accueille du lundi au samedi, dans un espace de 200 m2. Un lieu chaleureux,familial où vous pourrez développer et découvrir votre plein potentiel.",
      img: "/assets/img/complexe.webp",
      button: {
        link: "/complexe",
        label: "Le complexe",
      },
      left: false,
    },
    {
      title: "prix <br/><span>flexibles</span>",
      desc: "Dunes propose à ses adhérents des forfait adapté en fonction des seances que vous voulez effectuez dans la semaine. Qu'attendez vous pour atteindre vos objectifs ?",
      img: "/assets/img/prix.webp",
      button: {
        link: "/tarifs",
        label: "Decouvrir nos forfaits",
      },
      left: true,
    },
  ];

  return (
    <div>
      <Head>
        <title>Dunes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="scroll">
        <Banner 
        phrase="Salle de sport situé à Saint-Quentin dans l'aisne, venez atteindre vos objectifs grâce à nos programmes d'entrainements adapté à chacun"
        videoSrc="/assets/video/DunesPromo.mp4"
        />
        {layouts.map((el, i) => {
          return el.left ? (
            <LeftLayout
            key={i}
              i={i}
              img={el.img}
              title={el.title}
              desc={el.desc}
              button={el.button}
            />
          ) : (
            <RightLayout
            key={i}
              i={i}
              img={el.img}
              title={el.title}
              desc={el.desc}
              button={el.button}
            />
          );
        })}
      </main>
    </div>
  );
}
