import Head from 'next/head'
import Banner from './components/global/layouts/Home/Banner/Banner'
import Coaches from './components/global/layouts/Home/coaches/Coaches'
import Intensity from './components/global/layouts/Home/Intensity/Intensity'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Dunes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="scroll">
        <Banner/>
        <Intensity/>
        <Coaches/>
      </main>
    </div>
  )
}
