import planning_data from "../planning.json"
import Head from "next/head";
import Banner from "../components/global/Banner/Banner";
import Planning from "../components/layouts/Plannings/Planning/Planning";

export default function Plannings () {

    return (
        <div>
          <Head>
            <title>Dunes</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
    
          <main id="scroll">
            <Banner imgSrc="/assets/img/coach.jpeg"/>
            <Planning data={planning_data}/>
          </main>
        </div>
      );
}