import Head from "next/head";
import Banner from "../components/global/Banner/Banner";
import PageEnd from "../components/global/pageEnd/PageEnd";
import LeftLayout from "../components/layouts/Home/leftLayoiut/LeftLayout";
import RightLayout from "../components/layouts/Home/rightLayout/rightLayout";

export default function Programmes () {

    const layouts = [
        {
          title: "Functional <span>training</span>",
          desc: "Développe les compétences fondamentales de la motricité sportive (endurance cardio-vasculaire, endurance musculaire, vitesse, coordination, agilité, souplesse, mobilité, puissance, force). Ces entraînements sont accessibles à tous et à tous les niveaux comme chacun de nos programmes.",
          img: "/assets/img/intensity.webp",
          button: {
            link: "/plannings",
            label: "Reserver mon spot",
          },
          left: false,
        },
        {
          title: "Haltérophilie <span>&</span> Gym",
          desc: "Tu désire améliorer tes entraînements functionnal? Ces classes te permettront d’accélérer ton processus d’apprentissage dans ces deux domaines fondamentaux des entraînements fonctionnels.",
          img: "/assets/img/intensity.webp",
          button: {
            link: "/plannings",
            label: "Reserver mon spot",
          },
          left: true,
        },
        {
          title: "Personal <span>trainer</span>",
          desc: "Ce programme te permet d’être encadré en individuel par nos coachs, un programme personnalisé sera établi en accord avec tes objectifs (performance, réhabilitation ou sport santé).",
          img: "/assets/img/intensity.webp",
          button: {
            link: "/plannings",
            label: "Reserver mon spot",
          },
          left: false,
        },
        {
          title: "Fit <span>&</span> Healthy",
          desc: "Si perdre du poids est ta priorité,tu as choisis le programme par excellence pour perdre du poids tout en gagnant en masse musculaire. Ce programme est composé de renforcement musculaire et d' exercice Cardio à haute intensité. Pour ceux qui le désirent nous vous guidons sur la phase alimentaire via nos partenaires nutrition.",
          img: "/assets/img/intensity.webp",
          button: {
            link: "/plannings",
            label: "Reserver mon spot",
          },
          left: true,
        },
        {
          title: "Open <span>training</span>",
          desc: "Ces créneaux sont ouverts aux personnes qui maîtrisent les fondamentaux,l’accès à ces créneaux doit être validé par nos coachs. Une fois validé, vous aurait donc libre accès à la salle. ",
          img: "/assets/img/intensity.webp",
          button: {
            link: "/plannings",
            label: "Reserver mon spot",
          },
          left: false,
        },
      ];
  
  return (
    <div>
      <Head>
        <title>Dunes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="scroll">
        <Banner imgSrc="/assets/img/programmes.webp" title="Adaptée votre entrainement" />
        {layouts.map((el, i) => {
          return el.left ? (
            <LeftLayout
            key={i}
              i={i}
              img={el.img}
              title={el.title}
              desc={el.desc}
              button={el.button}
            />
          ) : (
            <RightLayout
              i={i}
              key={i}
              img={el.img}
              title={el.title}
              desc={el.desc}
              button={el.button}
            />
          );
        })}
        <PageEnd video_url='/assets/video/tarif.mp4' desc='Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc quis lorem quam. Nullam velit ante, scelerisque nec velit a, imperdiet pretium ipsum. Sed aliquam dui velit, ac finibus tellus vehicula quis.' title="Reservez votre essaie gratuit"/>
      </main>
    </div>
  );
}