import Head from "next/head";
import Banner from "../components/global/Banner/Banner";
import PageEnd from "../components/global/pageEnd/PageEnd";
import Coaches from "../components/layouts/Staff/coaches/Coaches";
import Tarifs from "../components/layouts/Tarifs/Tarifs/Tarifs";
import bareme from "../tarif.json";

export default function Tarif() {
  return (
    <div>
      <Head>
        <title>Dunes</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main id="scroll">
        <Banner
          title="tarifs ajusté pour tous"
          imgSrc="/assets/img/staffbanner.webp"
        />
        {bareme.map((el, i) => {
          return <Tarifs key={i} data={el} i={i} />;
        })}
        <PageEnd
          video_url="/assets/video/tarif.mp4"
          desc="N'hésitez pas à venir tester notre salle en faisant une demande de réservation via notre formulaire"
          title="Reservez votre essai gratuit"
          url="/contact"
        />
      </main>
    </div>
  );
}
